FROM node:16 AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/api

COPY package.json .
COPY package-lock.json .

RUN yarn global add @nestjs/cli
RUN yarn install --production=true

RUN apt-get -q update && apt-get -qy install netcat

COPY . .
RUN yarn build

CMD ["sh", "-c", "yarn start:prod"]